### ISSUE TITLE
Code style problem

### ISSUE THREAD

**Issue by Piterden** [jwagner/normalmap.js#3]
1. `var` is deprecated, use `const/let`

2. Next construction is wrong:
```js
if (canvas == null) // TypeError if canvas was not set!!!!!

if (typeof canvas === 'undefined') // The correct method!
```

3. Use classes
```js
class Normalmap {
    constructor (options) {
        this.options = Object.assign({
            metalness: 1,
            roughness: 1,
            ambient: 1,
            baseColor: new Float32Array([0.5, 0.5, 0.5])
        }, options)

        if (typeof options.canvas === 'undefined') {
            throw new Error('normalmap() canvas is required')
        }

        if (typeof options.normalMap === 'undefined') {
            throw new Error('normalmap() normalMap is required')
        }

        this.canvas = options.canvas
        this.defines = new Defines(options)
    }
}

class Defines {
    constructor (options, defines = {}) {
        Object.assign(this, defines)

        this.USE_BASE_COLOR_MAP = +options.baseColorMap
        this.USE_MATERIAL_MAP = +options.materialMap
        this.USE_AMBIENT_MAP = +options.ambientMap
        this.USE_SSS = +options.subSurfaceScattering
        this.USE_FXAA = +options.antiAliasing || undefined
        this.USE_SINGLE_PASS = +options.singlePass || undefined
    }
}
```

4. Choose yourself:
```js
'canvas repeat singlePass'.split() // ['canvas repeat singlePass']
'canvas repeat singlePass'.split(' ') // ['canvas', 'repeat', 'singlePass']
```

To be continued...

**Comment by jwagner** [comment]
Hello Piterden,

Thank you for having a look at my code, I'm always open for suggestions but please don't tell me what to do.
 
This code is generally written to be ES5 compatible in order to run in all browsers that support WebGL.
I'm not entirely sure why I used the const declarations in there but I guess it didn't hurt since it's supported by all browsers which support WebGL.

1. Again, this is ES5 code. But out of curiosity can you point me to the spec which marks var as deprecated? I can't recall reading that.
2. I guess you refer to line 23. In that case var is always defined by line 21. So I'd argue that this is correct.
3. It's ES5 code. It's not intended to be particularly object oriented.
4. That does look wrong. I'll have a look.
